name: bipupu
description: "Bipupu - 宇宙传讯"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0" # 允许 Dart 3.10 到 3.11，不轻易跨入未来的 4.0
  flutter: ">=3.38.0"
dependencies:
  animate_do: ^4.2.0
  dio: ^5.9.1
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.1.1
  flutter_hooks: ^0.21.3+1
  flutter_local_notifications: ^20.1.0
  flutter_riverpod: ^3.2.1

  hooks_riverpod: ^3.2.1
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.11.0
  path_provider: ^2.1.5
  retrofit: ^4.9.2
  riverpod_annotation: ^4.0.2
  shadcn_ui: ^0.46.1
  shared_preferences: ^2.5.3
  sherpa_onnx: ^1.12.25
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1

  json_serializable: ^6.13.0
  retrofit_generator: ^10.2.1
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
