
services:
  flutter-admin:
    image: ${FLUTTER_ADMIN_IMAGE}
    container_name: bipupu-flutter-admin
    restart: unless-stopped
    ports:
      - "8080:80"  # Assuming nginx on port 80 inside container
    networks:
      - bipupu-net

networks:
  bipupu-net:
    external: true
    name: bipupu-net