name: bipupu
description: "A Cyber-BIPIpager App"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 状态管理与路由
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1

  # 硬件与权限
  flutter_blue_plus: ^2.0.2
  permission_handler: ^11.3.1
  device_info_plus: ^12.3.0
  package_info_plus: ^8.1.0

  # 音频与 AI
  sound_stream: ^0.4.2
  audioplayers: ^6.1.0
  just_audio: ^0.10.5
  audio_session: ^0.1.6
  piper_tts_plugin:
    git:
      url: https://github.com/dev-6768/piper_tts_plugin.git
      ref: dev-6768-v0.0.3
  vosk_flutter:
    git:
      url: https://github.com/alphacep/vosk-flutter.git

  # 数据存储与网络
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.1.2
  web_socket_channel: ^2.2.0
  connectivity_plus: ^7.0.0

  # 图像处理
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  image: ^4.2.0
  cached_network_image: ^3.4.1

  # 国际化
  intl: ^0.20.2
  easy_localization: ^3.0.7
  flutter_localizations:
    sdk: flutter

  # 后台服务与通知
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.2.0
  flutter_local_notifications: ^20.0.0

  # 工具类
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.8

dependency_overrides:
  archive: ^4.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icon/
    - assets/images/operators/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
